env:
  es6: true
  node: true
  browser: false
parserOptions:
  ecmaVersion: 2020
  sourceType: module
extends:
  - prettier
plugins:
  - prettier
rules:
  prettier/prettier:
    - error
    - printWidth: 120
      singleQuote: true
      trailingComma: all
      semi: false
      proseWrap: never
      bracketSpacing: false
